keywords:
  - image segmentation
  - self-supervised learning
  - representation learning
  - image generation
  - object detection
  - transfer learning
  - transformers
  - adversarial training
  - generative adversarial networks
  - model compressions
  - image segmentation
  - few-shot learning
  - natural language
  - graph
  - colorization
  - depth estimation
  - point cloud
  - structured data
  - optical flow
  - reinforcement learning
  - super resolution
  - attention
  - tabular
  - unsupervised learning
  - semi-supervised learning
  - explainable
  - radiance field
  - decision tree
  - time series
  - molecule
  - large language models
  - llms
  - language models
  - image classification
  - document image classification
  - encoder
  - decoder
  - multimodal
  - multimodal deep learning
